services:
  registry:
    build:
      context: ./minicloud-registry
      dockerfile: Dockerfile.fedora

  gateway:
    build:
      context: ./minicloud-gateway
      dockerfile: Dockerfile.fedora
    depends_on:
      - registry

  monitor:
    build:
      context: ./minicloud-monitor
      dockerfile: Dockerfile.fedora
    depends_on:
      - gateway

  vault:
    build:
      context: ./minicloud-vault
      dockerfile: Dockerfile.fedora
    depends_on:
      - registry

  runner:
    build:
      context: ./minicloud-runner
      dockerfile: Dockerfile.fedora
    depends_on:
      - vault
